# MYSQL properties
spring.application.name=DemoRentalServices
spring.datasource.url=jdbc:mysql://localhost:3306/rental_db
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Spring JPA
spring.jpa.hibernate.ddl-auto=update 
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
server.port=8080

#Redis via Docker Desktop

# Redis Docker Desktop Connection Settings
spring.data.redis.host=localhost
spring.data.redis.port=6379


# Maximum size of a single uploaded file
spring.servlet.multipart.max-file-size=20MB

# Maximum size of the entire request
spring.servlet.multipart.max-request-size=20MB